modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
    modId="properproxyprotocol"
    version="${version}"
    displayName="Proper Proxy Protocol"
    description="Adds proxy protocol support to Minecraft servers."

[[mixins]]
    config="properproxyprotocol.mixins.json"

[[dependencies.properproxyprotocol]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.properproxyprotocol]]
    modId="architectury"
    type="required"
    versionRange="[19.0.0,)"
    ordering="NONE"
    side="BOTH"
