modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
    modId="proxyprotocolthatworks"
    version="${version}"
    displayName="ProxyProtocolThatWorks"
    description="Adds proxy protocol support to Minecraft servers."

[[mixins]]
    config="pptw.mixins.json"

[[dependencies.proxyprotocolthatworks]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.proxyprotocolthatworks]]
    modId="architectury"
    type="required"
    versionRange="[19.0.0,)"
    ordering="NONE"
    side="BOTH"
